/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as CategorySidebarRouteImport } from './app/_categorySidebar'
import { Route as ScanIndexRouteImport } from './app/scan/index'
import { Route as OrderIndexRouteImport } from './app/order/index'
import { Route as OrderHistoryIndexRouteImport } from './app/order-history/index'
import { Route as CategorySidebarIndexRouteImport } from './app/_categorySidebar/index'
import { Route as ApiSearchIndexRouteImport } from './app/api/search/index'
import { Route as CategorySidebarProductsIndexRouteImport } from './app/_categorySidebar/products/index'
import { Route as CategorySidebarCollectionIndexRouteImport } from './app/_categorySidebar/$collection/index'
import { Route as CategorySidebarProductsCategoryRouteRouteImport } from './app/_categorySidebar/products/$category/route'
import { Route as CategorySidebarProductsCategoryIndexRouteImport } from './app/_categorySidebar/products/$category/index'
import { Route as CategorySidebarProductsCategorySubcategoryIndexRouteImport } from './app/_categorySidebar/products/$category/$subcategory/index'
import { Route as CategorySidebarProductsCategorySubcategoryProductIndexRouteImport } from './app/_categorySidebar/products/$category/$subcategory/$product/index'

const CategorySidebarRoute = CategorySidebarRouteImport.update({
  id: '/_categorySidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderHistoryIndexRoute = OrderHistoryIndexRouteImport.update({
  id: '/order-history/',
  path: '/order-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySidebarIndexRoute = CategorySidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategorySidebarRoute,
} as any)
const ApiSearchIndexRoute = ApiSearchIndexRouteImport.update({
  id: '/api/search/',
  path: '/api/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySidebarProductsIndexRoute =
  CategorySidebarProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => CategorySidebarRoute,
  } as any)
const CategorySidebarCollectionIndexRoute =
  CategorySidebarCollectionIndexRouteImport.update({
    id: '/$collection/',
    path: '/$collection/',
    getParentRoute: () => CategorySidebarRoute,
  } as any)
const CategorySidebarProductsCategoryRouteRoute =
  CategorySidebarProductsCategoryRouteRouteImport.update({
    id: '/products/$category',
    path: '/products/$category',
    getParentRoute: () => CategorySidebarRoute,
  } as any)
const CategorySidebarProductsCategoryIndexRoute =
  CategorySidebarProductsCategoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CategorySidebarProductsCategoryRouteRoute,
  } as any)
const CategorySidebarProductsCategorySubcategoryIndexRoute =
  CategorySidebarProductsCategorySubcategoryIndexRouteImport.update({
    id: '/$subcategory/',
    path: '/$subcategory/',
    getParentRoute: () => CategorySidebarProductsCategoryRouteRoute,
  } as any)
const CategorySidebarProductsCategorySubcategoryProductIndexRoute =
  CategorySidebarProductsCategorySubcategoryProductIndexRouteImport.update({
    id: '/$subcategory/$product/',
    path: '/$subcategory/$product/',
    getParentRoute: () => CategorySidebarProductsCategoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof CategorySidebarIndexRoute
  '/order-history': typeof OrderHistoryIndexRoute
  '/order': typeof OrderIndexRoute
  '/scan': typeof ScanIndexRoute
  '/products/$category': typeof CategorySidebarProductsCategoryRouteRouteWithChildren
  '/$collection': typeof CategorySidebarCollectionIndexRoute
  '/products': typeof CategorySidebarProductsIndexRoute
  '/api/search': typeof ApiSearchIndexRoute
  '/products/$category/': typeof CategorySidebarProductsCategoryIndexRoute
  '/products/$category/$subcategory': typeof CategorySidebarProductsCategorySubcategoryIndexRoute
  '/products/$category/$subcategory/$product': typeof CategorySidebarProductsCategorySubcategoryProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof CategorySidebarIndexRoute
  '/order-history': typeof OrderHistoryIndexRoute
  '/order': typeof OrderIndexRoute
  '/scan': typeof ScanIndexRoute
  '/$collection': typeof CategorySidebarCollectionIndexRoute
  '/products': typeof CategorySidebarProductsIndexRoute
  '/api/search': typeof ApiSearchIndexRoute
  '/products/$category': typeof CategorySidebarProductsCategoryIndexRoute
  '/products/$category/$subcategory': typeof CategorySidebarProductsCategorySubcategoryIndexRoute
  '/products/$category/$subcategory/$product': typeof CategorySidebarProductsCategorySubcategoryProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_categorySidebar': typeof CategorySidebarRouteWithChildren
  '/_categorySidebar/': typeof CategorySidebarIndexRoute
  '/order-history/': typeof OrderHistoryIndexRoute
  '/order/': typeof OrderIndexRoute
  '/scan/': typeof ScanIndexRoute
  '/_categorySidebar/products/$category': typeof CategorySidebarProductsCategoryRouteRouteWithChildren
  '/_categorySidebar/$collection/': typeof CategorySidebarCollectionIndexRoute
  '/_categorySidebar/products/': typeof CategorySidebarProductsIndexRoute
  '/api/search/': typeof ApiSearchIndexRoute
  '/_categorySidebar/products/$category/': typeof CategorySidebarProductsCategoryIndexRoute
  '/_categorySidebar/products/$category/$subcategory/': typeof CategorySidebarProductsCategorySubcategoryIndexRoute
  '/_categorySidebar/products/$category/$subcategory/$product/': typeof CategorySidebarProductsCategorySubcategoryProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order-history'
    | '/order'
    | '/scan'
    | '/products/$category'
    | '/$collection'
    | '/products'
    | '/api/search'
    | '/products/$category/'
    | '/products/$category/$subcategory'
    | '/products/$category/$subcategory/$product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order-history'
    | '/order'
    | '/scan'
    | '/$collection'
    | '/products'
    | '/api/search'
    | '/products/$category'
    | '/products/$category/$subcategory'
    | '/products/$category/$subcategory/$product'
  id:
    | '__root__'
    | '/_categorySidebar'
    | '/_categorySidebar/'
    | '/order-history/'
    | '/order/'
    | '/scan/'
    | '/_categorySidebar/products/$category'
    | '/_categorySidebar/$collection/'
    | '/_categorySidebar/products/'
    | '/api/search/'
    | '/_categorySidebar/products/$category/'
    | '/_categorySidebar/products/$category/$subcategory/'
    | '/_categorySidebar/products/$category/$subcategory/$product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CategorySidebarRoute: typeof CategorySidebarRouteWithChildren
  OrderHistoryIndexRoute: typeof OrderHistoryIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
  ScanIndexRoute: typeof ScanIndexRoute
  ApiSearchIndexRoute: typeof ApiSearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_categorySidebar': {
      id: '/_categorySidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CategorySidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-history/': {
      id: '/order-history/'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof OrderHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_categorySidebar/': {
      id: '/_categorySidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CategorySidebarIndexRouteImport
      parentRoute: typeof CategorySidebarRoute
    }
    '/api/search/': {
      id: '/api/search/'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_categorySidebar/products/': {
      id: '/_categorySidebar/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof CategorySidebarProductsIndexRouteImport
      parentRoute: typeof CategorySidebarRoute
    }
    '/_categorySidebar/$collection/': {
      id: '/_categorySidebar/$collection/'
      path: '/$collection'
      fullPath: '/$collection'
      preLoaderRoute: typeof CategorySidebarCollectionIndexRouteImport
      parentRoute: typeof CategorySidebarRoute
    }
    '/_categorySidebar/products/$category': {
      id: '/_categorySidebar/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof CategorySidebarProductsCategoryRouteRouteImport
      parentRoute: typeof CategorySidebarRoute
    }
    '/_categorySidebar/products/$category/': {
      id: '/_categorySidebar/products/$category/'
      path: '/'
      fullPath: '/products/$category/'
      preLoaderRoute: typeof CategorySidebarProductsCategoryIndexRouteImport
      parentRoute: typeof CategorySidebarProductsCategoryRouteRoute
    }
    '/_categorySidebar/products/$category/$subcategory/': {
      id: '/_categorySidebar/products/$category/$subcategory/'
      path: '/$subcategory'
      fullPath: '/products/$category/$subcategory'
      preLoaderRoute: typeof CategorySidebarProductsCategorySubcategoryIndexRouteImport
      parentRoute: typeof CategorySidebarProductsCategoryRouteRoute
    }
    '/_categorySidebar/products/$category/$subcategory/$product/': {
      id: '/_categorySidebar/products/$category/$subcategory/$product/'
      path: '/$subcategory/$product'
      fullPath: '/products/$category/$subcategory/$product'
      preLoaderRoute: typeof CategorySidebarProductsCategorySubcategoryProductIndexRouteImport
      parentRoute: typeof CategorySidebarProductsCategoryRouteRoute
    }
  }
}

interface CategorySidebarProductsCategoryRouteRouteChildren {
  CategorySidebarProductsCategoryIndexRoute: typeof CategorySidebarProductsCategoryIndexRoute
  CategorySidebarProductsCategorySubcategoryIndexRoute: typeof CategorySidebarProductsCategorySubcategoryIndexRoute
  CategorySidebarProductsCategorySubcategoryProductIndexRoute: typeof CategorySidebarProductsCategorySubcategoryProductIndexRoute
}

const CategorySidebarProductsCategoryRouteRouteChildren: CategorySidebarProductsCategoryRouteRouteChildren =
  {
    CategorySidebarProductsCategoryIndexRoute:
      CategorySidebarProductsCategoryIndexRoute,
    CategorySidebarProductsCategorySubcategoryIndexRoute:
      CategorySidebarProductsCategorySubcategoryIndexRoute,
    CategorySidebarProductsCategorySubcategoryProductIndexRoute:
      CategorySidebarProductsCategorySubcategoryProductIndexRoute,
  }

const CategorySidebarProductsCategoryRouteRouteWithChildren =
  CategorySidebarProductsCategoryRouteRoute._addFileChildren(
    CategorySidebarProductsCategoryRouteRouteChildren,
  )

interface CategorySidebarRouteChildren {
  CategorySidebarIndexRoute: typeof CategorySidebarIndexRoute
  CategorySidebarProductsCategoryRouteRoute: typeof CategorySidebarProductsCategoryRouteRouteWithChildren
  CategorySidebarCollectionIndexRoute: typeof CategorySidebarCollectionIndexRoute
  CategorySidebarProductsIndexRoute: typeof CategorySidebarProductsIndexRoute
}

const CategorySidebarRouteChildren: CategorySidebarRouteChildren = {
  CategorySidebarIndexRoute: CategorySidebarIndexRoute,
  CategorySidebarProductsCategoryRouteRoute:
    CategorySidebarProductsCategoryRouteRouteWithChildren,
  CategorySidebarCollectionIndexRoute: CategorySidebarCollectionIndexRoute,
  CategorySidebarProductsIndexRoute: CategorySidebarProductsIndexRoute,
}

const CategorySidebarRouteWithChildren = CategorySidebarRoute._addFileChildren(
  CategorySidebarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CategorySidebarRoute: CategorySidebarRouteWithChildren,
  OrderHistoryIndexRoute: OrderHistoryIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
  ScanIndexRoute: ScanIndexRoute,
  ApiSearchIndexRoute: ApiSearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
